apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: jupiter-logger  
spec:
  selector:
    app : elasticsearch-master
    component: elasticsearch
    release: elasticsearch
  ports:
    - name: db
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: monitoring
      protocol: TCP
      port: 9300
      targetPort: 9300
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: NodePort