apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  namespace: jupiter-logger
spec:
  selector: 
    app: kibana
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 5601 
      # nodePort: 30000